config/routes.rb
Seddit::Application.routes.draw do
  root to: "static_pages#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

#   Rails UI is deprecated.  All user interface should be through Backbone.
#
#   resources :users, only: [:show]
#
#   This route will redirect to the appropriate Backbone view.
  resources :sub_seddits, only: [:show, :index], path: "s"
#     resources :posts, only: [:new, :create]
#   end
#   resources :posts, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#   resources :comments, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#
#   resources :votes, only: [:create, :update]

  namespace :api, :defaults => { :format => :json } do
    resources :sub_seddits, only: [:index, :show, :create, :update, :destroy],
    path: "s" do
      resources :posts, only: [:index]
      resource :user_subs, only: [:create, :update, :destroy], path: "favorite"
    end
    resources :posts, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:index, :create]
    end
    resources :comments, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:create]
    end

    resources :votes, only: [:create, :update, :destroy]
  end
end

app/views/navbar/_navbar_header.html.erb
<button type="button" class="navbar-toggle" data-toggle="collapse"
  data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="#">Seddit</a>
<!-- end navbar header -->

app/views/navbar/_signed_in_navbar_els.html.erb
<ul class="nav navbar-nav navbar-left">
  <div class="dropdown">
    <button class="btn dropdown-toggle" type="button"
      id="favorited-subs-dropdown-btn" data-toggle="dropdown">
      Your Favorite Subs
      <span class="caret"></span>
    </button>

    <ul id="favorited-subs" class="dropdown-menu"
      aria-labelledby="favorited-subs-dropdown-btn">
      <% current_user.favorite_subs.each do |sub| %>
        <li><a href="<%= "#{root_url}#/s/#{sub.name}" %>"><%= sub.name%></a></li>
      <% end %>
    </ul>
  </div>
</ul>

<ul class="nav navbar-nav navbar-right">
  <li>
    <div id="loading-icon" class="hidden"></div>
  </li>
  <li>
    <p class="navbar-text">Welcome, <%= current_user.username %>!</p>
  </li>
  <li>
    <%= button_to "Sign Out", session_url, method: :delete,
    class: "btn navbar-btn btn-danger"%>
  </li>
</ul>
<!-- end navbar body -->

app/views/navbar/_signed_out_navbar_els.html.erb
<ul class="nav navbar-nav navbar-left">
</ul>

<ul class="nav navbar-nav navbar-right">
  <li>
    <div id="loading-icon" class="hidden"></div>
  </li>
  <li><p class="navbar-text">Not signed in.</p></li>

  <li><a href="<%= new_session_url%>"
    class="btn navbar-btn btn-success">Sign In</a>
  </li>

  <li><a href="<%= new_user_url%>"
    class="btn navbar-btn btn-primary">Sign Up</a>
  </li>
</ul>
<!-- end navbar body -->