config/routes.rb
Seddit::Application.routes.draw do
  root to: "static_pages#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

#   Rails UI is deprecated.  All user interface should be through Backbone.
#
#   resources :users, only: [:show]
#
#   This route will redirect to the appropriate Backbone view.
  resources :sub_seddits, only: [:show, :index], path: "s"
#     resources :posts, only: [:new, :create]
#   end
#   resources :posts, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#   resources :comments, only: [:show] do
#     resources :comments, only: [:new, :create]
#   end
#
#   resources :votes, only: [:create, :update]

  namespace :api, :defaults => { :format => :json } do
    resources :sub_seddits, only: [:index, :show, :create, :update, :destroy],
    path: "s" do
      resources :posts, only: [:index]
      resource :user_subs, only: [:create, :update, :destroy], path: "favorite"
    end
    resources :posts, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:index, :create]
    end
    resources :comments, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:create]
    end

    resources :votes, only: [:create, :update, :destroy]
  end
end

app/models/sub_seddit.rb
# == Schema Information
#
# Table name: sub_seddits
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  owner_id   :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class SubSeddit < ActiveRecord::Base
  extend FriendlyId
  validates :name, :owner, presence: true
  validates :name, uniqueness: true
  validate :is_url_safe

  has_many :posts, inverse_of: :sub, foreign_key: :sub_id, dependent: :destroy
  belongs_to :owner, class_name: "User", inverse_of: :owned_subs
  has_many :user_subs, inverse_of: :sub, foreign_key: :sub_id, dependent: :destroy
  has_many :followers, through: :user_subs, source: :user

  friendly_id :name, :use => :slugged

  def is_url_safe
    if /[\W\s]/.match(self.name)
      errors.add(:sub_seddit,
      "name must contain only alphanumeric characters and underscores")
    end
  end
end

app/controllers/api/sub_seddits_controller.rb
class Api::SubSedditsController < ApplicationController
  before_action :ensure_signed_in, only: [:update, :destroy, :create]
  before_action :verify_ownership, only: [:update, :destroy]

  def index
    @subs = SubSeddit.includes(:owner, :followers)
      .order(:followers_count).order('lower(name)')
      .page(params[:page].to_i);
    render :index, locals: {subs: @subs}
  end

  def show
    @sub = SubSeddit.includes(:followers, posts: [:comments, :votes, :owner])
      .friendly.find(params[:id].to_s.downcase)
    render :show, locals: {sub: @sub}
  end

  def create
    @sub = current_user.owned_subs.build(sub_params)
    if @sub.save
      render :show, locals: {sub: @sub}
    else
      render :json => @sub.errors.full_messages, status: 422
    end
  end

  def update
    #@sub found in verify_ownership
    if @sub.update_attributes(sub_params)
      render :show, locals: {sub: @sub}
    else
      render :json => @sub.errors.full_messages, status: 422
    end
  end

  def destroy
    #@sub found in verify_ownership
    if @sub
      @sub.destroy
      render :show, locals: {sub: @sub}
    else
      head 404
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:name)
  end

  def verify_ownership
    @sub = SubSeddit.includes(:owner).find(params[:id])
    head 403 unless @sub.owner == current_user
  end
end

app/controllers/sub_seddits_controller.rb
class SubSedditsController < ApplicationController
  # Rails UI is deprecated.  All content UI should be through Backbone.

before_action :ensure_signed_in, only: [:new, :create]

  def index
    #Redirect to Backbone version; note root_url already ends with a "/"
    redirect_to "#{root_url}#"
  end

  def new
    @sub = SubSeddit.new
    render :new, locals: {sub: @sub}
  end

  def create
    @sub = current_user.owned_subs.build(sub_params)
    if @sub.save
      flash[:notice] = "Sub-seddit successfully created!"
      redirect_to sub_seddit_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new, locals: {sub: @sub}
    end
  end

  def show
    #Redirect to Backbone version; note root_url already ends with a "/"
    redirect_to "#{root_url}#/s/#{params[:id]}"
#    Deprecated Rails UI
#    @sub = SubSeddit.includes(posts:[:comments, :votes, :owner]).find(params[:id])
#    render :show, locals: {sub: @sub, posts: @sub.posts}
  end

#   def edit
#   end
#
#   def update
#   end
#
#   def destroy
#   end
  private
  def sub_params
    params.require(:sub).permit(:name)
  end
end

app/helpers/api/sub_seddits_helper.rb
module Api::SubSedditsHelper
end

app/helpers/sub_seddits_helper.rb
module SubSedditsHelper
  # Rails UI is deprecated.  All content UI should be through Backbone.
end

app/views/sub_seddits/_form.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<div class="form-container">
  <form action="<%= sub_seddits_url %>" method="POST">
    <%= csrf_token %>

    <div class="form-group">
      <label>Title:
      <input type="text"
        name="sub[name]"
        class="form-control"
        value="<%= sub.name %>"
        placeholder="Title"></input>
      </label>
    </div>

    <input type="submit" class="btn btn-success" value="Create Sub!"></input>
  </form>
</div>

app/views/sub_seddits/_post.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<li class="post" data-id="<%= post.id %>">
  <%= render "votable/karma", model: post %>
  <div class="post-link">
    <a href="<%= post_url(post) %>"><%= post.title %></a>
  </div>
  <div class="post-num-comments">
    (<%= post.num_comments %> comments)
  </div>
</li>

app/views/sub_seddits/new.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<h1>Create a Sub-Seddit</h1>

<%= render "form", sub: sub %>

app/views/sub_seddits/show.html.erb
<p>This UI has been deprecated.  Please visit <a href="">the new homepage.</a></p>

<h1>Welcome to the <%= sub.name %> sub-seddit!</h1>

<h3>This page is currently under construction.</h3>

<ul id="posts">
  <% posts.each do |post| %>
    <%= render "post", post: post %>
  <% end %>
</ul>